FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY bin/scheduler /k8s-vgpu/bin/scheduler
COPY docker/entrypoint.sh /k8s-vgpu/bin/entrypoint.sh
COPY lib /k8s-vgpu/lib
ENV PATH="/k8s-vgpu/bin:${PATH}"
ENTRYPOINT ["scheduler"]
